---
- name: Install mysql
  apt:
    name: "{{ item }}"
    state: present
  loop:
    - python3-mysqldb
    - mysql-server
    - mysql-client

- name: Check if mysql is started and enabled on boot
  service: "name=mysql state=started enabled=true"

#- name: Populate service facts
#  ansible.builtin.service_facts:

- name: create wordpress database
  mysql_db:
    name: "{{ wp_db_name }}"
    state: present

- name: create wordpress database user
  mysql_user:
    name: "{{ wp_db_user }}"
    password: "{{ wp_db_password }}"
    priv: "{{ wp_db_name }}.*:ALL"
    state: present
  notify:
    - restart mysqld

- name: Ensure MySQL is started and enabled on boot.
  service: "name=mysql state=started enabled=true"