---
- name: Export http and https proxy
  ansible.builtin.shell:
    cmd: "export {{ item }}='http://10.115.58.1:8080'"
  loop:
    - HTTP_PROXY
    - HTTPS_PROXY

- name: Import epel repo
  dnf:
    name: epel-release
    state: present

- name: Install php
  yum:
    name: 
      - '@php:7.4'
      - 'php'
      - 'php-cli'
      - 'php-fpm'
      - 'php-common'
      - 'php-mysqlnd'
      - 'php-json'
      - 'php-opcache'
      - 'php-mbstring'
      - 'php-xml'
      - 'php-gd'
      - 'php-curl'

- name: Change nginx user and group in /etc/php-fpm.d/www.conf
  ansible.builtin.replace:
    path: /etc/php-fpm.d/www.conf
    regexp: "{{ item }} apache"
    replace: "{{ item }} nginx"
  loop:
    - user = 
    - group = 

- name: restart php-fpm
  service:
    name: php-fpm
    state: restarted
    enabled: yes